In [2]:
import numpy as np
np.random.seed(7)

In [8]:
s = np.ones((2,3))

In [9]:
s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
s[-1] = np.zeros(3)

In [11]:
s

array([[1., 1., 1.],
       [0., 0., 0.]])

In [5]:
np.zeros(3)

array([0., 0., 0.])